// js/fieldHelp.js
// Field metadata from HealthDCAT-AP v6 specification spreadsheet.
// Covers Dataset, Distribution, and Kind (contact point) sheets.
//
// Keys are camelCase and intended to match state.data keys used in app.js.
// Distribution fields are prefixed with "dist_".
// Contact point (Kind) fields are prefixed with "contact_".

/* global FIELD_HELP */
const FIELD_HELP = {

  // ===========================================================
  // DATASET fields
  // ===========================================================

  accessRights: {
    label: 'access rights',
    uri: 'dct:accessRights',
    definition: 'Information about who access the resource or an indication of its security status.',
    vocabulary: 'http://publications.europa.eu/resource/authority/access-right',
    usageNote: 'Information that indicates whether the Dataset is publicly accessible, has access restrictions or is not public. It is foreseen that one of the three options have to be used: public, restricted, non-public.\n    Open Data (Public): The dataset is available under general open data rules, such as those covered by the High Value Datasets Implementing Regulation.\n    Protected Data (Restricted): The dataset contains protected data and is accessible only under specific conditions, as outlined in regulations like the Data Governance Act.\n    Sensitive Data (Non public): The dataset includes resources that may contain sensitive or personal information, falling under regulations such as the EHDS Regulation.\n\nSince most data contain personal information, these datasets will need to take the value \'non-public\' for the access rights property.',
    requirement: 'Mandatory',
    range: 'dct:RightsStatement (IRI)',
    cardinality: '1',
    iknlExample: ':restricted',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#access-rights',
  },
  analytics: {
    label: 'analytics',
    uri: 'healthdcatap:analytics',
    definition: 'An analytics distribution of the dataset.',
    usageNote: 'Publishers are encouraged to provide URLs pointing to document repositories where users can access or request associated resources such as technical reports of the dataset, quality measurements, usability indicators,... Note that HealthDCAT-AP mentions also API endpoints or analytics services, but these would not be Distriutions but rather DatasetServices.',
    requirement: 'Recommended',
    range: 'dcat:Distribution',
    cardinality: '0..n',
    iknlExample: 'https://iknl.nl/nkr/uitleg-nkr-cijfers https://nkr-cijfers.iknl.nl',
    iknlComment: 'zijn er andere bestanden of rapporten die we kunnen gebruiken jaarrapporten in het nederlands. ziektespecifieke rapporten.',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#analytics',
  },
  applicableLegislation: {
    label: 'applicable legislation',
    uri: 'dcatap:applicableLegislation',
    definition: 'The legislation that is applicable to this resource.',
    usageNote: 'The ELI of the EHDS was published in March 2025 and can now be included as the applicable legislation mandating that the dataset has to be made public.\nFor health datasets, the value must include the ELI of the EHDS Regulation (http://data.europa.eu/eli/reg/2025/327/oj).\nAs multiple legislations may apply to the resource the maximum cardinality is not limited.\n\nWhile the applicable legislation indicates which legislation mandates the publication of the dataset, the legal basis property (also in Datasets) described the legal basis for initial collection and processing of (personal) data.',
    requirement: 'Mandatory',
    range: 'eli:LegalResource (IRI)',
    cardinality: '1..n',
    iknlExample: 'http://data.europa.eu/eli/reg/2025/327/oj',
    iknlComment: 'Wetgeving die publicatie voorschrijft: EHDS. Daarnaast de verplichting tot publicatie op grond van subsidievoorwaarden  ministerie VWS.',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#applicable-legislation',
  },
  codeValues: {
    label: 'code values',
    uri: 'healthdcatap:hasCodeValues',
    definition: 'Health classifications and their codes associated with the dataset',
    usageNote: 'Inside this property, you can provide the coding system of the dataset in the form of wikidata URI (example: https://www.wikidata.org/entity/P494 for ICD-10 ID) and the URI of the value that describes the dataset (example: https://icd.who.int/browse10/2019/en#/Y59.0 for viral vaccines)',
    requirement: 'Recommended',
    range: 'skos:Concept (IRI)',
    cardinality: '0..n',
    iknlComment: 'Alle codes van Haemoto -> ICD-o-4. disease classes here and complete list of variables etc in the sample distribution. haem5 voor lympfomen en voor leukemien ook. -alle 8000 morphology coding',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#code-values',
  },
  codingSystem: {
    label: 'coding system',
    uri: 'healthdcatap:hasCodingSystem',
    definition: 'Coding systems in use (ex: ICD-10-CM, DGRs, SNOMED=CT, ...)',
    usageNote: 'This property provides informatio on which coding systems are in use inside your dataset. For this, wikidata URIs must be used.',
    requirement: 'Recommended',
    range: 'dct:Standard (IRI)',
    cardinality: '0..n',
    iknlExample: 'https://www.wikidata.org/wiki/Property:P563_ICD-0 risico classificaties voor de haematologie, (vergelijkbaar met stadiering)',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#coding-system',
  },
  conformsTo: {
    label: 'conforms to',
    uri: 'dct:conformsTo',
    definition: 'An established standard to which the described resource conforms.',
    usageNote: 'If your data conforms to an established standard or specification, use this property to indicate which one. The wikidata URI of the specification must be used. Example: https://www.wikidata.org/wiki/Q19597236 for FHIR.',
    requirement: 'Recommended',
    range: 'dct:Standard (IRI)',
    cardinality: '0..n',
    iknlComment: 'geen haematologie brede standaarden. 15 specifieke ziektebeelden met elk eigen standaarden etc.',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#conforms-to',
  },
  contactPoint: {
    label: 'contact point',
    uri: 'dcat:contactPoint',
    definition: 'Relevant contact information for the cataloged resource.',
    usageNote: 'This property points to a contact point (department or person) that can answer questions about the dataset. Details on how to describe these are provided under class vcard:Kind.\nWhenever possible, use a general contact information (for example from a department) instead of contact information of an individual.',
    requirement: 'Mandatory',
    range: 'vcard:Kind',
    cardinality: '1',
    iknlExample: 'gegevensaanvraag@iknl.nl',
    iknlComment: 'KIND tabblad',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#contact-point',
  },
  creator: {
    label: 'creator',
    uri: 'dct:creator',
    definition: 'An entity responsible for making the resource.',
    usageNote: 'This property points to a person (known as Agent) responsible for generating the dataset. In most cases, this should be the project’s Principal Investigator, provided they consent to being listed in the catalogue. If not, the associated department or institute may be specified instead.',
    requirement: 'Mandatory',
    range: 'foaf:Agent',
    cardinality: '1..n',
    iknlExample: 'Stichting Integraal Kankercentrum Nederland (IKNL)',
    iknlComment: 'Aanvullen obv agent tab',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#creator',
  },
  description: {
    label: 'description',
    uri: 'dct:description',
    definition: 'An account of the resource.',
    usageNote: 'Brief description of the dataset. You can repeat this property in multiple languages. Example: \'\'Collection of physiological data of Healthy Brain Study participants. This collection includes measurements via biowearables for heart rate, oxygenation, systolic and diastolic measures and stress levels.\'\'',
    requirement: 'Mandatory',
    range: 'rdfs:Literal',
    cardinality: '1..n',
    iknlExample: 'The Netherlands Cancer Registry (NCR) has been the national source of cancer data since 1989, providing comprehensive and reliable statistics on cancer in the Netherlands. Maintained by the Netherlands Comprehensive Cancer Organisation (IKNL), the NCR is a cornerstone of cancer control—supporting efforts from prevention and early detection to treatment, survivorship, and palliative care',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#description',
  },
  distribution: {
    label: 'distribution',
    uri: 'dcat:distribution',
    definition: 'An available Distribution for the Dataset.',
    usageNote: 'Metadata element used as a key link to the class Distribution.',
    requirement: 'Recommended',
    range: 'dcat:Distribution',
    cardinality: '0..n',
    iknlExample: 'csv',
    iknlComment: 'use fhir omop etc in conforms to in distribution. however how to tackle federated omop and do we have multiple distributions.',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#distribution',
  },
  documentation: {
    label: 'documentation',
    uri: 'foaf:page',
    definition: 'A page or document about this thing.',
    usageNote: 'The value of this property is the IRI directing to the web-page or document about the dataset.',
    requirement: 'Recommended',
    range: 'foaf:Document (IRI)',
    cardinality: '0..n',
    iknlExample: 'https://iknl.nl/getmedia/ce4ead48-ba30-4b10-8df8-955e4c6f1c18/NKR_Itemset_Hemato-oncologie_ALL_april2022_IKNL.pdf',
    iknlComment: 'ander document?',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#documentation',
  },
  frequency: {
    label: 'frequency',
    uri: 'dct:accrualPeriodicity',
    definition: 'The frequency with which items are added to a collection.',
    vocabulary: 'http://publications.europa.eu/resource/authority/frequency',
    usageNote: 'The value of this property should be the IRI from the listed controlled vocabulary indicating the frequency at which the dataset is updated.\nFor example: http://publications.europa.eu/resource/authority/frequency/WEEKLY',
    requirement: 'Recommended',
    range: 'skos:Concept (IRI)',
    cardinality: '0..1',
    iknlExample: 'http://publications.europa.eu/resource/authority/frequency/DAILY',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#frequency',
  },
  geographicalCoverage: {
    label: 'geographical coverage',
    uri: 'dct:spatial',
    definition: 'Spatial characteristics of the resource.',
    vocabulary: 'EU Vocabularies Continents Named Authority List',
    usageNote: 'The EU Vocabularies Name Authority Lists must be used for continents, countries and places that are in those lists; if a particular location is not in one of the mentioned Named Authority Lists, Geonames URIs must be used. For districts or neighbourhoods in NL, the Dutch vocab can be used. However, it might in many cases be desirable to keep the geographical coverage broader (eg. indicating that NL is covered), to not expose detailed information of subject\'s locations.',
    requirement: 'Recommended',
    range: 'dct:Location (IRI)',
    cardinality: '0..n',
    iknlExample: 'NLD',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#geographical-coverage',
  },
  hasVersion: {
    label: 'has version',
    uri: 'dcat:hasVersion',
    definition: 'This resource has a more specific, versioned resource.',
    usageNote: 'Indicate the dataset which is the other version of the current dataset.',
    requirement: 'Recommended',
    range: 'dcat:Dataset',
    cardinality: '0..n',
    iknlComment: 'https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#dataset-has-version',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#has-version',
  },
  healthTheme: {
    label: 'health theme',
    uri: 'healthdcatap:healthTheme',
    definition: 'A category of the Dataset or tag describing the Dataset.',
    usageNote: 'This property is a structured way to tag the dataset with different health themes. This could include, for example, the specific disease the dataset is about. More details can be provided, if desirable, in the keywords property. Current status: the HealthDCAT-AP working group is currently exploring is other sources (ontologies, thesauri) can be used for this, next to Wikidata. To access Wikidata, click on the link in the controlled vocabulary column and search for your desired theme there.',
    requirement: 'Recommended',
    range: 'skos:Concept (IRI)',
    cardinality: '0..n',
    iknlExample: 'https://www.wikidata.org/wiki/Q162555 - oncology (cancer-disease)',
    iknlComment: 'haematology, tumor types',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#health-theme',
  },
  identifier: {
    label: 'identifier',
    uri: 'dct:identifier',
    definition: 'An unambiguous reference to the resource within a given context.',
    usageNote: 'Current status: Health-RI is currently working on a strategy for persistant identifiers for, among other things, datasets. Until a solid solution has been found, we propose the following temporary solution:\nIf your data is published in a repository, fill in with the provided DOI (Example: https://doi.org/10.34894/ZLOYOJ). If not, use the identifier of the dataset as generated in the FAIR data point (FDP). Ensure that metadata is updated if your situation changes.',
    requirement: 'Mandatory',
    range: 'rdfs:Literal',
    cardinality: '1',
    iknlComment: 'downside with the FDP a new iditifier each time updates etc. new ID. -> for now FDP identifier (also recommendation of TEHDAS use local metadat tooling identifier)',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#identifier',
  },
  inSeries: {
    label: 'in series',
    uri: 'dcat:inSeries',
    definition: 'A dataset series of which the dataset is part.',
    usageNote: 'This property points to which Dataset Series the Dataset is part of.',
    requirement: 'Recommended',
    range: 'dcat:DatasetSeries',
    cardinality: '0..n',
    iknlExample: 'NKR',
    iknlComment: 'dataset series = NKR (A collection of datasets that are published separately, but share some characteristics that group them)',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#in-series',
  },
  isReferencedBy: {
    label: 'is referenced by',
    uri: 'dct:isReferencedBy',
    definition: 'A related resource that references, cites, or otherwise points to the described resource.',
    usageNote: 'The value of this property is the IRI of the doi to the publication or other related resource.\nFor example: https://doi.org/10.1186/s13690-021-00709-x',
    requirement: 'Recommended',
    range: 'rdfs:Resource (IRI)',
    cardinality: '0..n',
    iknlExample: 'https://iknl.nl/international/ncr',
    iknlComment: 'https://iknl.nl/nkr/over-nkr @NL??- rapporten ed',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#is-referenced-by',
  },
  keyword: {
    label: 'keyword',
    uri: 'dcat:keyword',
    definition: 'A keyword or tag describing the resource.',
    usageNote: 'Add keywords to increase dataset discoverability. You can include keywords in different languages, submitting each keyword as a separate entry. Example: Physiological measures, Heart Rate, Stress Measures.',
    requirement: 'Mandatory',
    range: 'rdfs:Literal',
    cardinality: '1..n',
    iknlExample: 'Haemotology; lymfeklierkanker, plasmaceltumoren, leukemie, myelodysplastische syndromen (MDS),  myeloproliferatieve aandoeningen (MPN) B-cellymfoom (DLBCL) en het folliculair lymfoom (FL), het multipel myeloom (MM) van de plasmaceltumoren.',
    iknlComment: 'an we use this for the use cases? PBCR? The Netherlands etc',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#keyword',
  },
  language: {
    label: 'language',
    uri: 'dct:language',
    definition: 'A language of the resource.',
    vocabulary: 'http://publications.europa.eu/resource/authority/language',
    usageNote: 'The language of the Dataset. For this property, the values from the EU Vocabularies Languages Named Authority List must be used. If your Dataset contains multiple languages, this property can be repeated.',
    requirement: 'Recommended',
    range: 'dct:LinguisticSystem (IRI)',
    cardinality: '0..n',
    iknlExample: '<skos:hasTopConcept rdf:resource="http://publications.europa.eu/resource/authority/language/NED"/>',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#language',
  },
  legalBasis: {
    label: 'legal basis',
    uri: 'dpv:hasLegalBasis',
    definition: 'Indicates use or applicability of a Legal Basis.',
    vocabulary: 'https://w3c.github.io/dpv/2.0/dpv/modules/legal_basis.html#vocab-legal-basis',
    usageNote: 'The legal basis can be provided as a value from the dpv taxonomy (see Controlled vocabulary column).\n\nWhile the applicable legislation indicates which legislation mandates the publication of the dataset, the legal basis property described the legal basis for initial collection and processing of (personal) data.\n\nExample value for this property could be: dpv:Consent',
    requirement: 'Recommended',
    range: 'dpv:LegalBasis',
    cardinality: '0..n',
    iknlExample: 'https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679 and https://wetten.overheid.nl/BWBR0040940/2021-07-01',
    iknlComment: 'Artikel 6 lid 1 sub f AVG jo. artikel 9 lid 2 sub j AVG jo. artikel 89 AVG jo. artikel 24 UAVG.',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#legal-basis',
  },
  maximumTypicalAge: {
    label: 'maximum typical age',
    uri: 'healthdcatap:maxTypicalAge',
    definition: 'Maximum typical age of the population within the dataset',
    usageNote: 'The approximate maximum age of subjects in the dataset, if applicable. Approximate age is given to protect potentially sensitive information of subjects in the dataset.',
    requirement: 'Recommended',
    range: 'xsd:non NegativeInteger',
    cardinality: '0..1',
    iknlExample: 'Oudste persoon- 100',
    iknlComment: 'International Cancer Survival Standard (ICSS)',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#maximum-typical-age',
  },
  minimumTypicalAge: {
    label: 'minimum typical age',
    uri: 'healthdcatap:minTypicalAge',
    definition: 'Minimum typical age of the population within the dataset',
    usageNote: 'The approximate minimum age of subjects in the dataset, if applicable. Approximate age is given to protect potentially sensitive information of subjects in the dataset.',
    requirement: 'Recommended',
    range: 'xsd:non NegativeInteger',
    cardinality: '0..1',
    iknlExample: '18',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#minimum-typical-age',
  },
  modificationDate: {
    label: 'modification date',
    uri: 'dct:modified',
    definition: 'Date on which the resource was changed.',
    usageNote: 'This property indicates changes to the dataset, not the metadata record. An absent value may mean the resource hasn\'t changed since publication, the modification date is unknown, or the resource is continuously updated.',
    requirement: 'Recommended',
    range: 'xsd:dateTime',
    cardinality: '0..1',
    iknlComment: 'absent means constantly updated',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#modification-date',
  },
  numberOfRecords: {
    label: 'number of records',
    uri: 'healthdcatap:numberOfRecords',
    definition: 'Size of the dataset in terms of the number of records',
    usageNote: 'Number of records inside a Dataset.',
    requirement: 'Recommended',
    range: 'xsd:NonNegativeInteger',
    cardinality: '0..1',
    iknlComment: 'constantly updated how to approach',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#number-of-records',
  },
  numberOfUniqueIndividuals: {
    label: 'number of unique infividuals',
    uri: 'healthdcatap:numberOfUniqueIndividuals',
    definition: 'Number of records for unique individuals.',
    usageNote: 'This property is not mandatory, since not all datasets might include data from individuals.',
    requirement: 'Recommended',
    range: 'xsd:NonNegativeInteger',
    cardinality: '0..1',
    iknlComment: 'each year an update with individuals and records and change the modification date?',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#number-of-unique-infividuals',
  },
  otherIdentifier: {
    label: 'other identifier',
    uri: 'adms:identifier',
    definition: 'Links a resource to an adms:Identifier class.',
    usageNote: 'Examples for secondary identifiers are MAST/ADS, DataCite, DOI, EZID or W3ID (if not used for the original identifier). This property makes use of another, small class: adms:Identifier, where you provide the identifier and the name of the identifier schema (eg. DOI).',
    requirement: 'Recommended',
    range: 'adms:Identifier',
    cardinality: '0..n',
    iknlExample: 'FDP : ID en bovenin , na beschikking DOI omdraaien',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#other-identifier',
  },
  personalData: {
    label: 'personal data',
    uri: 'dpv:hasPersonalData',
    definition: 'Indicates association with Personal Data.',
    vocabulary: 'https://w3c.github.io/dpv/2.0/pd/',
    usageNote: 'The different types of personal information that are collected in the dataset can be indicated with this property. Values can be picked from the dpv taxonomy (see controlled vocabulary column).\nFor example: dpv-pd:Gender',
    requirement: 'Recommended',
    range: 'dpv:PersonalData',
    cardinality: '0..n',
    iknlExample: 'Gender; Region; Demographic; income bracket; health record; health history;',
    iknlComment: 'ink_ses. (Mediaan inkomen in postcodegebied als proxy voor sociaaleconomische status (SES)) https://w3c.github.io/dpv/2.0/pd/ discuss with tumorteam',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#personal-data',
  },
  populationCoverage: {
    label: 'population coverage',
    uri: 'healthdcatap:populationCoverage',
    definition: 'A definition of the population within the dataset',
    usageNote: 'This field is a free text description of the population covered in the dataset. For example, "Adults aged 18–65 diagnosed with type 2 diabetes in the Netherlands between 2015 and 2020".',
    requirement: 'Recommended',
    range: 'rdfs:Literal',
    cardinality: '0..n',
    iknlExample: 'Adults aged 18–100 diagnosed with haematological cancer in the Netherlands since 1989',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#population-coverage',
  },
  publisher: {
    label: 'publisher',
    uri: 'dct:publisher',
    definition: 'An entity responsible for making the resource available.',
    usageNote: 'This property identifies the organisation or individual responsible for making the dataset available. For datasets, this is typically the employer of the data creators. In simple cases, the dataset publisher may be the same as the catalog publisher. In more complex settings, such as when datasets come from multiple institutions within a consortium, the consortium should be listed as the publisher where possible. If no formal consortium can be specified, provide the information of the contributing organizations or individuals under dct:creator instead. For more details, refer to the Agent class.',
    requirement: 'Mandatory',
    range: 'foaf:Agent',
    cardinality: '1',
    iknlExample: 'Integraal kankercentrum Nederland (IKNL) identifier: https://ror.org/03g5hcd33',
    iknlComment: 'Agent',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#publisher',
  },
  purpose: {
    label: 'purpose',
    uri: 'dpv:hasPurpose',
    definition: 'Indicates association with Purpose.',
    vocabulary: 'https://w3c.github.io/dpv/2.1/dpv/#vocab-purposes',
    usageNote: 'One (or many) category or sub-category of the purposes can be chosen from the taxonomy provided by dpv (see controlled vocabulary column).\nExample value could be: dpv:ResearchAndDevelopment.',
    requirement: 'Recommended',
    range: 'dpv:Purpose',
    cardinality: '0..n',
    iknlExample: 'ResearchAndDevelopment;  LegalCompliance;  	Provide Official Statistics',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#purpose',
  },
  qualifiedAttribution: {
    label: 'qualified attribution',
    uri: 'prov:qualifiedAttribution',
    definition: 'Attribution is the ascribing of an entity to an agent.',
    usageNote: 'This property makes use of another small class (prov:Attribution). There, you can choose one of the roles as listed in the controlled vocabulary and link that to a specific Agent (expressed with foaf:Agent). Note that for HealthDCAT-AP, the list of roles might be extended in the future.\nExample: https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml#processor\n\nUse this property if you would like to indicate the funder of the (research project that resulted in creation of the) dataset.\nThe value for role then becomes: https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml#funder',
    requirement: 'Recommended',
    range: 'prov:Attribution',
    cardinality: '0..n',
    iknlExample: 'provider/owner/user/distributor/pointofcontact/processor/publisher/collaborator/editor/mediator/rightsholder',
    iknlComment: 'Op eerste aanzicht lijkt dat IKNL meerdere rollen heef, use palga lbz and municipalities, vektis. -> as dct:Source? how to tackle this. gebruik palga etc als contribitor',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#qualified-attribution',
  },
  qualifiedRelation: {
    label: 'qualified relation',
    uri: 'dcat:qualifiedRelation',
    definition: 'Link to a description of a relationship with another resource.',
    usageNote: 'This property makes use of another small class (dcat:Relationship), in which you can indicate the related resource (via its identifier) and the nature of the relation (based on a controlled vocabulary, which is described in the information of the class).',
    requirement: 'Recommended',
    range: 'dcat:Relationship',
    cardinality: '0..n',
    iknlComment: 'KIJK NAAR TAB \'\' relationship\'',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#qualified-relation',
  },
  qualityAnnotation: {
    label: 'quality annotation',
    uri: 'dqv:hasQualityAnnotation',
    definition: 'Refers to a quality annotation.',
    usageNote: 'This property makes use of another small class (dqv:QualityCertificate), in which you indicate the IRI of the quality certificate, linked to the described resource (via the identifier of the dataset). See that class for more information.',
    requirement: 'Recommended',
    range: 'dqv:QualityCertificate',
    cardinality: '0..n',
    iknlComment: 'quantum? ISO? REQueST?',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#quality-annotation',
  },
  releaseDate: {
    label: 'release date',
    uri: 'dct:issued',
    definition: 'Date of formal issuance of the resource.',
    usageNote: 'This property should point to the first known date of issuance, such as the publication date in a data repository. Example: 2023-12-10T13:16:10.246Z.',
    requirement: 'Recommended',
    range: 'xsd:dateTime',
    cardinality: '0..1',
    iknlExample: 'Eerste keer publicatie dataset - 1989',
    iknlComment: 'Dit kan zijn moment van aanvraag, moment van verstrekking dataset of moment van downloaden set voor publicatie?',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#release-date',
  },
  retentionPeriod: {
    label: 'retention period',
    uri: 'healthdcatap:retentionPeriod',
    definition: 'A temporal period which the dataset is available for secondary use.',
    usageNote: 'This property makes use of the class dct:PeriodOfTime, in which a start and end date should be provided.',
    requirement: 'Recommended',
    range: 'dct:PeriodOfTime',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#retention-period',
  },
  sample: {
    label: 'sample',
    uri: 'adms:sample',
    definition: 'Links to a sample of an Asset (which is itself an Asset).',
    usageNote: 'This property makes use of the dcat:Distribution class to describe a sample distribution of the dataset, which can be anonymized or synthetic data, or the data dictionary provided in CSVW format. This is currently further developed by the TEHDAS2 program. More information can be found here: https://healthdcat-ap.github.io/#sample-distribution',
    requirement: 'Recommended',
    range: 'dcat:Distribution',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#sample',
  },
  source: {
    label: 'source',
    uri: 'dct:source',
    definition: 'A related resource from which the described resource is derived.',
    usageNote: 'Indicate the dataset on which this described dataset is based.',
    requirement: 'Recommended',
    range: 'dcat:Dataset',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#source',
  },
  status: {
    label: 'status',
    uri: 'adms:status',
    definition: 'The status of the Asset in the context of a particular workflow process.',
    vocabulary: 'https://publications.europa.eu/resource/authority/dataset-status',
    usageNote: 'This property makes use of a controlled vocabulary to indicate the status of the described dataset.\nFor example: http://publications.europa.eu/resource/authority/dataset-status/COMPLETED',
    requirement: 'Recommended',
    range: 'skos:Concept (IRI)',
    cardinality: '0..1',
    iknlExample: 'Completed',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#status',
  },
  temporalCoverage: {
    label: 'temporal coverage',
    uri: 'dct:temporal',
    definition: 'Temporal characteristics of the resource.',
    usageNote: 'The start and end date of the period that the dataset covers. This property makes use of a small class: Period of Time, in which a start and end date can be given.',
    requirement: 'Recommended',
    range: 'dct:PeriodOfTime',
    cardinality: '0..n',
    iknlExample: 'From 1989 till …',
    iknlComment: 'hoe verhoudt dit tov 41',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#temporal-coverage',
  },
  temporalResolution: {
    label: 'temporal resolution',
    uri: 'dcat:temporalResolution',
    definition: 'Minimum time period resolvable in the dataset.',
    usageNote: 'If the dataset is a time-series, this should correspond to the spacing of items in the series. For other kinds of dataset, this property will usually indicate the smallest time difference between items in the dataset. The time period has to be provided in the xsd:duration format.',
    requirement: 'Recommended',
    range: 'xsd:duration',
    cardinality: '0..1',
    iknlComment: 'Bij QoL kan dit voorkomen. Haemato niet',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#temporal-resolution',
  },
  theme: {
    label: 'theme',
    uri: 'dcat:theme',
    definition: 'A main category of the resource. A resource can have multiple themes.',
    vocabulary: 'Dataset Theme Vocabulary',
    usageNote: 'This property should use a controlled vocabulary. In the Health Data Catalogue, all datasets will use the theme \'HEAL\' (http://publications.europa.eu/resource/authority/data-theme/HEAL), but additional values from the same vocabulary are allowed.',
    requirement: 'Mandatory',
    range: 'skos:Concept (IRI)',
    cardinality: '1..n',
    iknlExample: '/data-theme/HEAL',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#theme',
  },
  title: {
    label: 'title',
    uri: 'dct:title',
    definition: 'A name given to the resource.',
    usageNote: 'Provide a unique title for your Dataset, which can be repeated in multiple languages. Example: Healthy Brain Study - Physiological Data',
    requirement: 'Mandatory',
    range: 'rdfs:Literal',
    cardinality: '1..n',
    iknlExample: 'haematological cancer dataset',
    iknlComment: 'RANK-Bestandsindeling-tumorsoort-2025.pdf',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#title',
  },
  type: {
    label: 'type',
    uri: 'dct:type',
    definition: 'The nature or genre of the resource.',
    vocabulary: 'Dataset-type authority table',
    usageNote: 'A recommended controlled vocabulary data-type is foreseen. Health datasets with personal information must use \'personal data\'. This list supports dataset categorization for the EU Open Data Portal. Currently, \'PERSONAL_DATA\' is not included in the EU vocabulary and cannot be filled out.',
    requirement: 'Recommended',
    range: 'skos:Concept (IRI)',
    cardinality: '0..n',
    iknlExample: 'STATISTICAL/ SYNTHETIC_DATA/ TEST_DATA/ TAXONOMY',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#type',
  },
  version: {
    label: 'version',
    uri: 'dcat:version',
    definition: 'The version indicator (name or identifier) of a resource.',
    usageNote: 'Suggested practice: track major_version.minor_version. Register a new identifier for major changes (e.g., 1.0.0 for an unchanged dataset).',
    requirement: 'Recommended',
    range: 'rdfs:Literal',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#version',
  },
  versionNotes: {
    label: 'version notes',
    uri: 'adms:versionNotes',
    definition: 'A description of changes between this version and the previous version of the Asset.',
    usageNote: 'Provide a short description of changes made to the dataset from the previous version.',
    requirement: 'Recommended',
    range: 'rdfs:Literal',
    cardinality: '0..n',
    iknlComment: 'Versie verschillen',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#version-notes',
  },
  wasGeneratedBy: {
    label: 'was generated by',
    uri: 'prov:wasGeneratedBy',
    definition: 'Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation.',
    usageNote: '',
    requirement: 'Recommended',
    range: 'prov:Activity',
    cardinality: '0..n',
    iknlComment: 'Is dit het tumorteam of gewoon IKNL',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#was-generated-by',
  },

  // ===========================================================
  // DISTRIBUTION fields (prefixed "dist_")
  // ===========================================================

  dist_accessService: {
    label: 'access service',
    uri: 'dcat:accessService',
    definition: 'A data service that gives access to the distribution of the dataset.',
    usageNote: 'This property links the distribution class to the corresponding data service(s).',
    requirement: 'Recommended',
    range: 'dcat:DataService',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#access-service',
  },
  dist_accessUrl: {
    label: 'access url',
    uri: 'dcat:accessURL',
    definition: 'A URL of the resource that gives access to a distribution of the dataset. E.g., landing page, feed, SPARQL endpoint.',
    usageNote: 'Add a link that points to where the dataset can be found. If it’s hosted in a Data Repository, include the link to its entry. For datasets not in a repository (like registries), but still available for secondary use, provide a link to an access request form or a webpage with instructions for accessing the data.',
    requirement: 'Mandatory',
    range: 'rdfs:Resource (IRI)',
    cardinality: '1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#access-url',
  },
  dist_applicableLegislation: {
    label: 'applicable legislation',
    uri: 'dcatap:applicableLegislation',
    definition: 'The legislation that is applicable to this resource.',
    usageNote: 'The legislation that mandates the creation or management of the Distribution.',
    requirement: 'Recommended',
    range: 'eli:LegalResource (IRI)',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#applicable-legislation',
  },
  dist_byteSize: {
    label: 'byte size',
    uri: 'dcat:byteSize',
    definition: 'The size of a distribution in bytes.',
    usageNote: 'Describes the size of the distribution (the actual file) in bytes, and is therefore expressed as a non-negative integer. If the actual size is not know, it can be estimated.',
    requirement: 'Mandatory',
    range: 'xsd:nonNegativeInteger',
    cardinality: '1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#byte-size',
  },
  dist_checksum: {
    label: 'checksum',
    uri: 'spdx:checksum',
    definition: 'The checksum property provides a mechanism that can be used to verify that the contents of a file or package have not changed.',
    usageNote: 'The checksum is related to the downloadURL. This property makes use of the spdx:Checksum class, which itself has two properties to indicate checksum algorithm and checksum value (see Checksum class for further details).',
    requirement: 'Recommended',
    range: 'spdx:Checksum',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#checksum',
  },
  dist_compressionFormat: {
    label: 'compression format',
    uri: 'dcat:compressFormat',
    definition: 'The compression format of the distribution in which the data is contained in a compressed form, e.g., to reduce the size of the downloadable file.',
    vocabulary: 'IANA Media Types',
    usageNote: 'It MUST be expressed using a media type as defined in the official register of media types managed by IANA.',
    requirement: 'Recommended',
    range: 'dct:MediaType (IRI)',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#compression-format',
  },
  dist_description: {
    label: 'description',
    uri: 'dct:description',
    definition: 'An account of the resource.',
    usageNote: 'Provide specific details about the distribution here, complementing the description of the related Dataset. This field can be repeated for different language versions of the description.',
    requirement: 'Recommended',
    range: 'rdfs:Literal',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#description',
  },
  dist_documentation: {
    label: 'documentation',
    uri: 'foaf:page',
    definition: 'A homepage for some thing.',
    usageNote: 'This page can contain additional information about the distribution.',
    requirement: 'Recommended',
    range: 'foaf:Document (IRI)',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#documentation',
  },
  dist_downloadUrl: {
    label: 'download URL',
    uri: 'dcat:downloadURL',
    definition: 'The URL of the downloadable file in a given format. E.g., CSV file or RDF file. The format is indicated by the distribution\'s dcterms:format and/or dcat:mediaType.',
    usageNote: 'If the dataset is openly accessible and available in a repository, you can directly include a link to the downloadable file here.',
    requirement: 'Recommended',
    range: 'rdfs:Resource (IRI)',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#download-url',
  },
  dist_format: {
    label: 'format',
    uri: 'dct:format',
    definition: 'The file format, physical medium, or dimensions of the resource.',
    vocabulary: 'http://publications.europa.eu/resource/authority/file-type',
    usageNote: 'This property can be used to describe a media format in more detail than "media type" (using IANA media type) when needed. Instances of this property should use a URL, e.g., from the File Type vocabulary. For instance, for mzML files the value of this property could be: http://edamontology.org/format_3244',
    requirement: 'Mandatory',
    range: 'dct:MediaTypeOrExtent (IRI)',
    cardinality: '1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#format',
  },
  dist_language: {
    label: 'language',
    uri: 'dct:language',
    definition: 'A language of the resource.',
    vocabulary: 'http://publications.europa.eu/resource/authority/language',
    usageNote: 'Indicates the natural language used in the Distribution, indicated with a value from the EU controlled vocabulary. Not all distributions might have a language, for example imaging data.\nNote that here the Health-RI model diverges from DCAT-AP NL, which allows maximum of 1 languages per Distribution. The Health-RI model allows multiple languages in the same Distribution.',
    requirement: 'Recommended',
    range: 'dct:LinguisticSystem (IRI)',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#language',
  },
  dist_license: {
    label: 'license',
    uri: 'dct:license',
    definition: 'A legal document giving official permission to do something with the resource.',
    vocabulary: 'https://definities.geostandaarden.nl/dcat-ap-nl/nl/',
    usageNote: 'For public data, use a Creative Commons (CC) license (see Geonovum options in the Controlled Vocabulary column). For most National Health Data Catalogue distributions, where data is not public, use the \'not open\' license from Geonovum and specify data reuse agreements in the dct:rights property.',
    requirement: 'Mandatory',
    range: 'dct:LicenceDocument (IRI)',
    cardinality: '1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#license',
  },
  dist_linkedSchemas: {
    label: 'linked schemas',
    uri: 'dct:conformsTo',
    definition: 'An established standard to which the described resource conforms.',
    usageNote: 'This property SHOULD be used to indicate the model, schema, ontology, view or profile that this representation of a dataset conforms to, in a machine-readable form. This is (generally) a complementary concern to the media-type or format. Use a reference to the official publication of the respective schema.',
    requirement: 'Recommended',
    range: 'dct:Standard (IRI)',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#linked-schemas',
  },
  dist_mediaType: {
    label: 'media type',
    uri: 'dcat:mediaType',
    definition: 'The media type of the distribution as defined by IANA.',
    vocabulary: 'IANA Media Types',
    usageNote: 'Use the specified vocabularies, prioritizing IANA media types whenever possible. If unavailable, consider other ontologies, such as ZonMw generic terms, to descibe the format.\nExample: https://www.iana.org/assignments/media-types/text/csv (for csv)\nIf IANA media types do not sufficiently describe the format, use "format" to describe it in more detail.',
    requirement: 'Recommended',
    range: 'dct:MediaType (IRI)',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#media-type',
  },
  dist_modificationDate: {
    label: 'modification date',
    uri: 'dct:modified',
    definition: 'Date on which the resource was changed.',
    usageNote: '',
    requirement: 'Recommended',
    range: 'xsd:dateTime',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#modification-date',
  },
  dist_packagingFormat: {
    label: 'packaging format',
    uri: 'dcat:packageFormat',
    definition: 'The package format of the distribution in which one or more data files are grouped together, e.g., to enable a set of related files to be downloaded together.',
    vocabulary: 'IANA Media Types',
    usageNote: 'It SHOULD be expressed using a media type as defined in the official register of media types managed by IANA.',
    requirement: 'Recommended',
    range: 'dct:MediaType (IRI)',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#packaging-format',
  },
  dist_releaseDate: {
    label: 'release date',
    uri: 'dct:issued',
    definition: 'Date of formal issuance of the resource.',
    usageNote: 'The date the dataset distribution was issued.',
    requirement: 'Recommended',
    range: 'xsd:dateTime',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#release-date',
  },
  dist_retentionPeriod: {
    label: 'retention period',
    uri: 'healthdcatap:retentionperiod',
    definition: 'A temporal period which the dataset is available for secondary use.',
    usageNote: 'This property makes use of the class dct:PeriodOfTime, in which a start and end date should be provided.',
    requirement: 'Recommended',
    range: 'dct:PeriodOfTime',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#retention-period',
  },
  dist_rights: {
    label: 'rights',
    uri: 'dct:rights',
    definition: 'Information about rights held in and over the resource.',
    usageNote: 'A statement that concerns all rights not addressed in fields License or Access rights. In case of not open data (as specified in the dct:licence property), further agreements regarding data reuse (eg. Data Transfer Agreement, DTA,) should be stated in this property.\nThe rights statement should be a free-text statement placed at an web-accessible location such that the value of this property is the IRI pointing to that statement.\nCurrent status: This recommendation on how to state data transfer/reuse conditions will be pilotted in 2025.',
    requirement: 'Mandatory',
    range: 'dct:RightsStatement (IRI)',
    cardinality: '1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#rights',
  },
  dist_status: {
    label: 'status',
    uri: 'adms:status',
    definition: 'The status of the Asset in the context of a particular workflow process.',
    vocabulary: 'EU Vocabularies Distribution Status',
    usageNote: 'It MUST take one of the values Completed, Deprecated, Under Development, Withdrawn from the provided controlled vocabulary.',
    requirement: 'Recommended',
    range: 'skos:Concept (IRI)',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#status',
  },
  dist_temporalResolution: {
    label: 'temporal resolution',
    uri: 'dcat:temporalResolution',
    definition: 'Minimum time period resolvable in the dataset.',
    usageNote: 'If applicable, this property indicates the minimum time period resolvable in the dataset distribution, expressed in xsd:duration format (see for more information here: https://www.w3schools.com/xml/schema_dtypes_date.asp)',
    requirement: 'Recommended',
    range: 'xsd:duration',
    cardinality: '0..1',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#temporal-resolution',
  },
  dist_title: {
    label: 'title',
    uri: 'dct:title',
    definition: 'A name given to the resource.',
    usageNote: 'A title given to the distribution. e.g., Data Access Request of Healthy Brain study',
    requirement: 'Recommended',
    range: 'rdfs:Literal',
    cardinality: '0..n',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#title',
  },

  // ===========================================================
  // KIND / contact point fields (prefixed "contact_")
  // ===========================================================

  contact_contactPage: {
    label: 'contact page',
    uri: 'vcard:hasURL',
    definition: 'To specify a uniform resource locator associated with the object.',
    usageNote: 'A webpage that either allows to make contact (i.e. a webform) or the information contains how to get into contact.',
    requirement: 'Recommended',
    range: 'rdfs:Resource  (IRI)',
    cardinality: '0..n',
    iknlExample: 'Contact & adres',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#contact-page',
  },
  contact_hasEmail: {
    label: 'has email',
    uri: 'vcard:hasEmail',
    definition: 'To specify the electronic mail address for communication with the object.',
    usageNote: 'When naming a contact point this information needs to be further specified with additional information, i.e., an email address. This email address does not need to be a direct contact to the person responsible for the management of the data, it could be a generic information email.\nThe email address has to be provided starting with mailto: prefix.\nFor example: mailto:info@example.com / mailto: jane.doe@example.com',
    requirement: 'Mandatory',
    range: 'rdfs:Resource  (IRI)',
    cardinality: '1',
    iknlExample: 'mailto:gegevensaanvraag@iknl.nl',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#has-email',
  },
  contact_formattedName: {
    label: 'formatted name',
    uri: 'vcard:fn',
    definition: 'The formatted text corresponding to the name of the object.',
    usageNote: 'Provide the full name of the contact point, such as the name of a person or department responsible for communication.',
    requirement: 'Mandatory',
    range: 'xsd:string',
    cardinality: '1',
    iknlExample: 'Vcard: NKR Analyse',
    specUrl: 'https://healthdataeu.pages.code.europa.eu/healthdcat-ap/releases/release-6/index.html#formatted-name',
  },
};

if (typeof module !== 'undefined') module.exports = FIELD_HELP;