// vocabularies.js — Controlled vocabulary lists for Health DCAT-AP v6

const VOCAB = {

  accessRights: [
    { label: 'Non-Public — requires HDAB mediation', uri: 'http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC' },
    { label: 'Restricted — specific access conditions apply', uri: 'http://publications.europa.eu/resource/authority/access-right/RESTRICTED' },
    { label: 'Public — openly accessible', uri: 'http://publications.europa.eu/resource/authority/access-right/PUBLIC' },
  ],

  legislation: [
    { label: 'EHDS Regulation (EU) 2024/1689', uri: 'http://data.europa.eu/eli/reg/2024/1689/oj' },
    { label: 'GDPR (EU) 2016/679', uri: 'http://data.europa.eu/eli/reg/2016/679/oj' },
    { label: 'ePrivacy Directive 2002/58/EC', uri: 'http://data.europa.eu/eli/dir/2002/58/oj' },
    { label: 'NEN 7510 (NL Health Data Security)', uri: 'https://www.nen.nl/nen-7510-2017-nl-230461' },
  ],

  healthCategories: [
    { label: 'Electronic Health Records (EHR)', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/ehr' },
    { label: 'Patient Registry', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/patient-registry' },
    { label: 'Clinical Trials Data', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/clinical-trials' },
    { label: 'Genomics / Biobank Data', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/genomics' },
    { label: 'Medical Imaging', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/medical-imaging' },
    { label: 'Claims / Reimbursement Data', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/claims' },
    { label: 'Laboratory / Diagnostic Results', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/laboratory' },
    { label: 'Prescription / Medication Data', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/medication' },
    { label: 'Population Health Survey', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/population-survey' },
    { label: 'Disease Registry', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/disease-registry' },
    { label: 'Wearable / IoT Health Data', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/wearable' },
    { label: 'Social Determinants of Health', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-category/social-determinants' },
  ],

  healthThemes: [
    { label: 'Cancer / Oncology', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/cancer' },
    { label: 'Cardiovascular Disease', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/cardiovascular' },
    { label: 'Rare Diseases', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/rare-diseases' },
    { label: 'Mental Health / Psychiatry', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/mental-health' },
    { label: 'Infectious Disease', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/infectious-disease' },
    { label: 'Diabetes / Endocrinology', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/diabetes' },
    { label: 'Respiratory Disease', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/respiratory' },
    { label: 'Neurology', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/neurology' },
    { label: 'Pediatrics', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/pediatrics' },
    { label: 'Maternal and Reproductive Health', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/maternal-health' },
    { label: 'Musculoskeletal', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/musculoskeletal' },
    { label: 'COVID-19', uri: 'http://data.europa.eu/r5r/healthdcat-ap/resource/health-theme/covid-19' },
  ],

  languages: [
    // 24 EU official languages
    { label: 'Bulgarian (bg)',    uri: 'http://publications.europa.eu/resource/authority/language/BUL', tag: 'bg' },
    { label: 'Croatian (hr)',     uri: 'http://publications.europa.eu/resource/authority/language/HRV', tag: 'hr' },
    { label: 'Czech (cs)',        uri: 'http://publications.europa.eu/resource/authority/language/CES', tag: 'cs' },
    { label: 'Danish (da)',       uri: 'http://publications.europa.eu/resource/authority/language/DAN', tag: 'da' },
    { label: 'Dutch (nl)',        uri: 'http://publications.europa.eu/resource/authority/language/NLD', tag: 'nl' },
    { label: 'English (en)',      uri: 'http://publications.europa.eu/resource/authority/language/ENG', tag: 'en' },
    { label: 'Estonian (et)',     uri: 'http://publications.europa.eu/resource/authority/language/EST', tag: 'et' },
    { label: 'Finnish (fi)',      uri: 'http://publications.europa.eu/resource/authority/language/FIN', tag: 'fi' },
    { label: 'French (fr)',       uri: 'http://publications.europa.eu/resource/authority/language/FRA', tag: 'fr' },
    { label: 'German (de)',       uri: 'http://publications.europa.eu/resource/authority/language/DEU', tag: 'de' },
    { label: 'Greek (el)',        uri: 'http://publications.europa.eu/resource/authority/language/ELL', tag: 'el' },
    { label: 'Hungarian (hu)',    uri: 'http://publications.europa.eu/resource/authority/language/HUN', tag: 'hu' },
    { label: 'Irish (ga)',        uri: 'http://publications.europa.eu/resource/authority/language/GLE', tag: 'ga' },
    { label: 'Italian (it)',      uri: 'http://publications.europa.eu/resource/authority/language/ITA', tag: 'it' },
    { label: 'Latvian (lv)',      uri: 'http://publications.europa.eu/resource/authority/language/LAV', tag: 'lv' },
    { label: 'Lithuanian (lt)',   uri: 'http://publications.europa.eu/resource/authority/language/LIT', tag: 'lt' },
    { label: 'Maltese (mt)',      uri: 'http://publications.europa.eu/resource/authority/language/MLT', tag: 'mt' },
    { label: 'Polish (pl)',       uri: 'http://publications.europa.eu/resource/authority/language/POL', tag: 'pl' },
    { label: 'Portuguese (pt)',   uri: 'http://publications.europa.eu/resource/authority/language/POR', tag: 'pt' },
    { label: 'Romanian (ro)',     uri: 'http://publications.europa.eu/resource/authority/language/RON', tag: 'ro' },
    { label: 'Slovak (sk)',       uri: 'http://publications.europa.eu/resource/authority/language/SLK', tag: 'sk' },
    { label: 'Slovenian (sl)',    uri: 'http://publications.europa.eu/resource/authority/language/SLV', tag: 'sl' },
    { label: 'Spanish (es)',      uri: 'http://publications.europa.eu/resource/authority/language/SPA', tag: 'es' },
    { label: 'Swedish (sv)',      uri: 'http://publications.europa.eu/resource/authority/language/SWE', tag: 'sv' },
    // EEA / EFTA
    { label: 'Icelandic (is)',    uri: 'http://publications.europa.eu/resource/authority/language/ISL', tag: 'is' },
    { label: 'Norwegian (no)',    uri: 'http://publications.europa.eu/resource/authority/language/NOR', tag: 'no' },
    // Candidate & neighbouring countries
    { label: 'Albanian (sq)',     uri: 'http://publications.europa.eu/resource/authority/language/SQI', tag: 'sq' },
    { label: 'Armenian (hy)',     uri: 'http://publications.europa.eu/resource/authority/language/HYE', tag: 'hy' },
    { label: 'Belarusian (be)',   uri: 'http://publications.europa.eu/resource/authority/language/BEL', tag: 'be' },
    { label: 'Bosnian (bs)',      uri: 'http://publications.europa.eu/resource/authority/language/BOS', tag: 'bs' },
    { label: 'Georgian (ka)',     uri: 'http://publications.europa.eu/resource/authority/language/KAT', tag: 'ka' },
    { label: 'Macedonian (mk)',   uri: 'http://publications.europa.eu/resource/authority/language/MKD', tag: 'mk' },
    { label: 'Moldovan (mo)',     uri: 'http://publications.europa.eu/resource/authority/language/RON', tag: 'mo' },
    { label: 'Montenegrin (cnr)',uri: 'http://publications.europa.eu/resource/authority/language/SRP', tag: 'cnr' },
    { label: 'Russian (ru)',      uri: 'http://publications.europa.eu/resource/authority/language/RUS', tag: 'ru' },
    { label: 'Serbian (sr)',      uri: 'http://publications.europa.eu/resource/authority/language/SRP', tag: 'sr' },
    { label: 'Turkish (tr)',      uri: 'http://publications.europa.eu/resource/authority/language/TUR', tag: 'tr' },
    { label: 'Ukrainian (uk)',    uri: 'http://publications.europa.eu/resource/authority/language/UKR', tag: 'uk' },
    // Other globally relevant
    { label: 'Arabic (ar)',       uri: 'http://publications.europa.eu/resource/authority/language/ARA', tag: 'ar' },
    { label: 'Chinese (zh)',      uri: 'http://publications.europa.eu/resource/authority/language/ZHO', tag: 'zh' },
    { label: 'Hindi (hi)',        uri: 'http://publications.europa.eu/resource/authority/language/HIN', tag: 'hi' },
    { label: 'Japanese (ja)',     uri: 'http://publications.europa.eu/resource/authority/language/JPN', tag: 'ja' },
  ],

  langTags: [
    { label: 'English (en)', tag: 'en' },
    { label: 'Dutch (nl)', tag: 'nl' },
    { label: 'German (de)', tag: 'de' },
    { label: 'French (fr)', tag: 'fr' },
    { label: 'Spanish (es)', tag: 'es' },
    { label: 'Italian (it)', tag: 'it' },
    { label: 'Swedish (sv)', tag: 'sv' },
    { label: 'Danish (da)', tag: 'da' },
  ],

  countries: [
    // EU member states (27)
    { label: 'Austria',          uri: 'http://publications.europa.eu/resource/authority/country/AUT' },
    { label: 'Belgium',          uri: 'http://publications.europa.eu/resource/authority/country/BEL' },
    { label: 'Bulgaria',         uri: 'http://publications.europa.eu/resource/authority/country/BGR' },
    { label: 'Croatia',          uri: 'http://publications.europa.eu/resource/authority/country/HRV' },
    { label: 'Cyprus',           uri: 'http://publications.europa.eu/resource/authority/country/CYP' },
    { label: 'Czech Republic',   uri: 'http://publications.europa.eu/resource/authority/country/CZE' },
    { label: 'Denmark',          uri: 'http://publications.europa.eu/resource/authority/country/DNK' },
    { label: 'Estonia',          uri: 'http://publications.europa.eu/resource/authority/country/EST' },
    { label: 'Finland',          uri: 'http://publications.europa.eu/resource/authority/country/FIN' },
    { label: 'France',           uri: 'http://publications.europa.eu/resource/authority/country/FRA' },
    { label: 'Germany',          uri: 'http://publications.europa.eu/resource/authority/country/DEU' },
    { label: 'Greece',           uri: 'http://publications.europa.eu/resource/authority/country/GRC' },
    { label: 'Hungary',          uri: 'http://publications.europa.eu/resource/authority/country/HUN' },
    { label: 'Ireland',          uri: 'http://publications.europa.eu/resource/authority/country/IRL' },
    { label: 'Italy',            uri: 'http://publications.europa.eu/resource/authority/country/ITA' },
    { label: 'Latvia',           uri: 'http://publications.europa.eu/resource/authority/country/LVA' },
    { label: 'Lithuania',        uri: 'http://publications.europa.eu/resource/authority/country/LTU' },
    { label: 'Luxembourg',       uri: 'http://publications.europa.eu/resource/authority/country/LUX' },
    { label: 'Malta',            uri: 'http://publications.europa.eu/resource/authority/country/MLT' },
    { label: 'Netherlands',      uri: 'http://publications.europa.eu/resource/authority/country/NLD' },
    { label: 'Poland',           uri: 'http://publications.europa.eu/resource/authority/country/POL' },
    { label: 'Portugal',         uri: 'http://publications.europa.eu/resource/authority/country/PRT' },
    { label: 'Romania',          uri: 'http://publications.europa.eu/resource/authority/country/ROU' },
    { label: 'Slovakia',         uri: 'http://publications.europa.eu/resource/authority/country/SVK' },
    { label: 'Slovenia',         uri: 'http://publications.europa.eu/resource/authority/country/SVN' },
    { label: 'Spain',            uri: 'http://publications.europa.eu/resource/authority/country/ESP' },
    { label: 'Sweden',           uri: 'http://publications.europa.eu/resource/authority/country/SWE' },
    // EEA / EFTA
    { label: 'Iceland',          uri: 'http://publications.europa.eu/resource/authority/country/ISL' },
    { label: 'Liechtenstein',    uri: 'http://publications.europa.eu/resource/authority/country/LIE' },
    { label: 'Norway',           uri: 'http://publications.europa.eu/resource/authority/country/NOR' },
    { label: 'Switzerland',      uri: 'http://publications.europa.eu/resource/authority/country/CHE' },
    // EU candidate countries
    { label: 'Albania',          uri: 'http://publications.europa.eu/resource/authority/country/ALB' },
    { label: 'Bosnia and Herzegovina', uri: 'http://publications.europa.eu/resource/authority/country/BIH' },
    { label: 'Georgia',          uri: 'http://publications.europa.eu/resource/authority/country/GEO' },
    { label: 'Moldova',          uri: 'http://publications.europa.eu/resource/authority/country/MDA' },
    { label: 'Montenegro',       uri: 'http://publications.europa.eu/resource/authority/country/MNE' },
    { label: 'North Macedonia',  uri: 'http://publications.europa.eu/resource/authority/country/MKD' },
    { label: 'Serbia',           uri: 'http://publications.europa.eu/resource/authority/country/SRB' },
    { label: 'Turkey',           uri: 'http://publications.europa.eu/resource/authority/country/TUR' },
    { label: 'Ukraine',          uri: 'http://publications.europa.eu/resource/authority/country/UKR' },
    // Other EHDS-relevant
    { label: 'United Kingdom',   uri: 'http://publications.europa.eu/resource/authority/country/GBR' },
    { label: 'Israel',           uri: 'http://publications.europa.eu/resource/authority/country/ISR' },
    { label: 'United States',    uri: 'http://publications.europa.eu/resource/authority/country/USA' },
    { label: 'Canada',           uri: 'http://publications.europa.eu/resource/authority/country/CAN' },
    { label: 'Australia',        uri: 'http://publications.europa.eu/resource/authority/country/AUS' },
    { label: 'Japan',            uri: 'http://publications.europa.eu/resource/authority/country/JPN' },
    // Supranational
    { label: 'European Union (multiple member states)', uri: 'http://publications.europa.eu/resource/authority/country/EU' },
  ],

  frequencies: [
    { label: 'Continuous', uri: 'http://publications.europa.eu/resource/authority/frequency/CONT' },
    { label: 'Daily', uri: 'http://publications.europa.eu/resource/authority/frequency/DAILY' },
    { label: 'Weekly', uri: 'http://publications.europa.eu/resource/authority/frequency/WEEKLY' },
    { label: 'Monthly', uri: 'http://publications.europa.eu/resource/authority/frequency/MONTHLY' },
    { label: 'Quarterly', uri: 'http://publications.europa.eu/resource/authority/frequency/QUARTERLY' },
    { label: 'Biannual (twice a year)', uri: 'http://publications.europa.eu/resource/authority/frequency/BIANNUAL' },
    { label: 'Annual', uri: 'http://publications.europa.eu/resource/authority/frequency/ANNUAL' },
    { label: 'Biennial (every 2 years)', uri: 'http://publications.europa.eu/resource/authority/frequency/BIENNIAL' },
    { label: 'Irregular', uri: 'http://publications.europa.eu/resource/authority/frequency/IRREG' },
    { label: 'Not planned / Static', uri: 'http://publications.europa.eu/resource/authority/frequency/NEVER' },
  ],

  fileFormats: [
    { label: 'CSV', uri: 'http://publications.europa.eu/resource/authority/file-type/CSV' },
    { label: 'JSON', uri: 'http://publications.europa.eu/resource/authority/file-type/JSON' },
    { label: 'XML', uri: 'http://publications.europa.eu/resource/authority/file-type/XML' },
    { label: 'Parquet', uri: 'http://publications.europa.eu/resource/authority/file-type/PARQUET' },
    { label: 'XLSX (Excel)', uri: 'http://publications.europa.eu/resource/authority/file-type/XLSX' },
    { label: 'PDF', uri: 'http://publications.europa.eu/resource/authority/file-type/PDF' },
    { label: 'RDF/Turtle', uri: 'http://publications.europa.eu/resource/authority/file-type/RDF_TURTLE' },
    { label: 'FHIR (JSON)', uri: 'http://publications.europa.eu/resource/authority/file-type/JSON_LD' },
    { label: 'DICOM (imaging)', uri: 'http://publications.europa.eu/resource/authority/file-type/DICOM' },
    { label: 'HL7 v2', uri: 'http://publications.europa.eu/resource/authority/file-type/HL7' },
  ],

  licenses: [
    { label: 'Creative Commons BY 4.0', uri: 'https://creativecommons.org/licenses/by/4.0/' },
    { label: 'Creative Commons BY-NC 4.0', uri: 'https://creativecommons.org/licenses/by-nc/4.0/' },
    { label: 'Creative Commons BY-SA 4.0', uri: 'https://creativecommons.org/licenses/by-sa/4.0/' },
    { label: 'Public Domain (CC0 1.0)', uri: 'https://creativecommons.org/publicdomain/zero/1.0/' },
    { label: 'Open Data Commons Attribution', uri: 'https://opendatacommons.org/licenses/by/1-0/' },
    { label: 'Proprietary / Restricted Access', uri: 'http://publications.europa.eu/resource/authority/licence/COM_REUSE' },
  ],

  publisherTypes: [
    { label: 'National Authority', uri: 'http://publications.europa.eu/resource/authority/publisher-type/NATIONAL_AUTHORITY' },
    { label: 'Regional Authority', uri: 'http://publications.europa.eu/resource/authority/publisher-type/REGIONAL_AUTHORITY' },
    { label: 'University / Research Institution', uri: 'http://publications.europa.eu/resource/authority/publisher-type/ACADEMIA_SCH_EDU' },
    { label: 'Hospital / Healthcare Provider', uri: 'http://publications.europa.eu/resource/authority/publisher-type/PUB_HOSPITAL' },
    { label: 'Non-governmental Organisation', uri: 'http://publications.europa.eu/resource/authority/publisher-type/NGO' },
    { label: 'Private Company', uri: 'http://publications.europa.eu/resource/authority/publisher-type/PRIVATE' },
  ],

  dataThemes: [
    { label: 'Health', uri: 'http://publications.europa.eu/resource/authority/data-theme/HEAL' },
    { label: 'Science and Technology', uri: 'http://publications.europa.eu/resource/authority/data-theme/TECH' },
    { label: 'Population and Society', uri: 'http://publications.europa.eu/resource/authority/data-theme/SOCI' },
    { label: 'Education, Culture, Sport', uri: 'http://publications.europa.eu/resource/authority/data-theme/EDUC' },
  ],

  mediaTypes: [
    { label: 'text/csv', uri: 'https://www.iana.org/assignments/media-types/text/csv' },
    { label: 'application/json', uri: 'https://www.iana.org/assignments/media-types/application/json' },
    { label: 'application/xml', uri: 'https://www.iana.org/assignments/media-types/application/xml' },
    { label: 'application/fhir+json', uri: 'https://www.iana.org/assignments/media-types/application/fhir+json' },
    { label: 'application/fhir+xml', uri: 'https://www.iana.org/assignments/media-types/application/fhir+xml' },
    { label: 'application/dicom', uri: 'https://www.iana.org/assignments/media-types/application/dicom' },
    { label: 'application/parquet', uri: 'https://www.iana.org/assignments/media-types/application/parquet' },
    { label: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', uri: 'https://www.iana.org/assignments/media-types/application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
    { label: 'text/plain', uri: 'https://www.iana.org/assignments/media-types/text/plain' },
  ],

  distributionStatuses: [
    { label: 'Completed', uri: 'http://purl.org/adms/status/Completed' },
    { label: 'Under Development', uri: 'http://purl.org/adms/status/UnderDevelopment' },
    { label: 'Deprecated', uri: 'http://purl.org/adms/status/Deprecated' },
    { label: 'Withdrawn', uri: 'http://purl.org/adms/status/Withdrawn' },
  ],

  compressionFormats: [
    { label: 'ZIP (.zip)', uri: 'https://www.iana.org/assignments/media-types/application/zip' },
    { label: 'GZIP (.gz)', uri: 'https://www.iana.org/assignments/media-types/application/gzip' },
    { label: 'TAR (.tar)', uri: 'https://www.iana.org/assignments/media-types/application/x-tar' },
    { label: '7-Zip (.7z)', uri: 'https://www.iana.org/assignments/media-types/application/x-7z-compressed' },
  ],

  relationRoles: [
    { label: 'Is Part Of', uri: 'http://www.iana.org/assignments/relation/ispartof' },
    { label: 'Has Part', uri: 'http://www.iana.org/assignments/relation/hasPart' },
    { label: 'Is Version Of', uri: 'http://www.iana.org/assignments/relation/isversionof' },
    { label: 'Has Version', uri: 'http://www.iana.org/assignments/relation/hasversion' },
    { label: 'Is Referenced By', uri: 'http://www.iana.org/assignments/relation/isreferencedby' },
    { label: 'References', uri: 'http://www.iana.org/assignments/relation/references' },
    { label: 'Replaces', uri: 'http://www.iana.org/assignments/relation/replaces' },
    { label: 'Is Replaced By', uri: 'http://www.iana.org/assignments/relation/isreplacedby' },
  ],

  attributionRoles: [
    { label: 'Author', uri: 'http://www.loc.gov/marc/relators/aut' },
    { label: 'Contributor', uri: 'http://www.loc.gov/marc/relators/ctb' },
    { label: 'Data Curator', uri: 'http://www.loc.gov/marc/relators/dtc' },
    { label: 'Data Manager', uri: 'http://www.loc.gov/marc/relators/dtm' },
    { label: 'Distributor', uri: 'http://www.loc.gov/marc/relators/dst' },
    { label: 'Principal Investigator', uri: 'http://www.loc.gov/marc/relators/rth' },
    { label: 'Researcher', uri: 'http://www.loc.gov/marc/relators/res' },
    { label: 'Rights Holder', uri: 'http://www.loc.gov/marc/relators/rhe' },
    { label: 'Sponsor', uri: 'http://www.loc.gov/marc/relators/spn' },
  ],

  legalBases: [
    { label: 'GDPR Art. 9(2)(a) — Explicit consent', uri: 'https://w3id.org/dpv/dpv-gdpr#A9-2-a' },
    { label: 'GDPR Art. 9(2)(c) — Vital interests', uri: 'https://w3id.org/dpv/dpv-gdpr#A9-2-c' },
    { label: 'GDPR Art. 9(2)(h) — Healthcare provision', uri: 'https://w3id.org/dpv/dpv-gdpr#A9-2-h' },
    { label: 'GDPR Art. 9(2)(i) — Public interest in public health', uri: 'https://w3id.org/dpv/dpv-gdpr#A9-2-i' },
    { label: 'GDPR Art. 9(2)(j) — Scientific or historical research', uri: 'https://w3id.org/dpv/dpv-gdpr#A9-2-j' },
    { label: 'EHDS Chapter IV — Secondary use of health data', uri: 'http://data.europa.eu/eli/reg/2024/1689/oj' },
  ],
};
